### ISSUE TITLE
[Bug]: Custom Fields - idea-custom-block missing label

### ISSUE THREAD

**Issue by rbento1096** [iter-idea/IDEA-Ionic7-extra#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature

Idea custom field should have the labels indicating what the field is about

![Screenshot 2023-08-25 at 13 51 35](https://github.com/iter-idea/IDEA-Ionic7-extra/assets/61906364/0c587689-e1dd-4ad1-ae3e-62064190dce4)

### Anomaly

With angular version 16, the field label is no longer shown

![Screenshot 2023-08-25 at 13 51 27](https://github.com/iter-idea/IDEA-Ionic7-extra/assets/61906364/7a30172b-87f6-4849-a83e-6e42fa8d0d8d)

### Cause

Update to Angular 16

> ion-checkbox now requires providing a label with either the default slot or the "aria-label" attribute.

> ion-select now requires providing a label with either the "label" property or the "aria-label" attribute.

### Example

Start a report on a scarlett model with a custom field on a front-end updated to angular 16

### On which environments did you encounter the bug?

dev

### What device are you seeing the problem on?

Desktop (MacOS)

### What browsers are you seeing the problem on?

Chrome

**Comment by rbento1096** [comment]
su iOS non si vedono proprio si vede solo il sfondo grigio e il check della checkbox

**Comment by uatisdeproblem** [comment]
Il problema era su Scarlett: nella `init.guard` non caricavamo correttamente le traduzioni; non c'è nulla da sistemare qui, chiudo.
